# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwifreecaTV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Kingfisher'
pod 'Alamofire'
pod 'SnapKit'
pod 'NVActivityIndicatorView'
pod 'MarqueeLabel'
pod 'AMShimmer'

  # Pods for TwifreecaTV

end
